config/routes.rb
Rails.application.routes.draw do 
  get 'sessions/new'
  get '/ingresar',to: 'sessions#new'
  get 'sessions/create'
  get 'sessions/destroy' 
  get 'users/create' 
  get 'users/new' 
   
  get 'welcome/index'
  resources :personas
  resources :users, only: [:new, :create, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index" 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    def welcome
        "¡Hola, #{self.email}!"
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
  helper_method :current_user

  def require_login
    redirect_to new_session_path unless session.include? :user_id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: %i[ show edit update destroy ]

  # GET /personas or /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1 or /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas or /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to persona_url(@persona), notice: "El registro de la persona fue creado exitosamente." }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1 or /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to persona_url(@persona), notice: "Registro de persona actualizado correctamente." }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1 or /personas/1.json
  def destroy
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url, notice: "El registro de persona fue eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def persona_params
      params.require(:persona).permit(:nombre, :fecha_nacimiento, :lugar_nacimiento, :estado_civil, :genero)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :new]

  def new
  end 

  def create
    session_params = params.permit(:email, :password)
    @user = User.find_by(email: session_params[:email])
    if @user && @user.authenticate(session_params[:password])
      if( @user.administrador==true)
        redirect_to new_persona_path
      else
      flash[:notice] = "Login valido!"
      session[:user_id] = @user.id
      redirect_to personas_path
      end
    else
      flash[:notice] = "¡Datos incorrectos verifique por favor!"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "¡Sesión cerrada exitosamente!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    
    def show
    end
  
    def index
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.valid?
        session[:user_id] = @user.id
        redirect_to @user
      else
        flash[:error] = "Error- please try to create an account again."
        redirect_to new_user_path
      end
    end
  
    private 
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoblacionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_with(model: persona, class: "contents") do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
        <% persona.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fecha_nacimiento %>
    <%= form.date_field :fecha_nacimiento, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :lugar_nacimiento %>
    <%= form.text_field :lugar_nacimiento, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :estado_civil %>
    <%= form.text_field :estado_civil, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :genero %>
    <%= form.text_field :genero, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/personas/_persona.html.erb
<style>
  .gradient {
    background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
  }
</style>
<body class="leading-normal tracking-normal text-white gradient text-left font-semibold text-1xl" style="font-family: 'Source Sans Pro', sans-serif;">


<div id="<%= dom_id persona %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nombre:</strong>
    <%= persona.nombre %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fecha nacimiento:</strong>
    <%= persona.fecha_nacimiento %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Lugar nacimiento:</strong>
    <%= persona.lugar_nacimiento %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Estado civil:</strong>
    <%= persona.estado_civil %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Genero:</strong>
    <%= persona.genero %>
  </p>

  <% if action_name != "show"%>
    <%= link_to "Mostrar registro de persona", persona, class: "text-gray-800 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Editar registro de persona', edit_persona_path(persona), class: "text-gray-800 rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>
</body>

app/views/personas/edit.html.erb
<style>
  .gradient {
    background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
  }
</style>
<body class="leading-normal tracking-normal text-gray-800 gradient text-left font-semibold text-1xl" style="font-family: 'Source Sans Pro', sans-serif;">

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Edición de registro de persona</h1>

  <%= render "form", persona: @persona %>

  <%= link_to "Mostrar este registro", @persona, class: "text-gray-800 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Regresara a lista de personas", personas_path, class: "text-gray-800 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
</body>

app/views/personas/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Personas</h1>
    <%= link_to 'Nuevo registro', new_persona_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="personas" class="min-w-full">
    <%= render @personas %>
  </div>
</div>

app/views/personas/new.html.erb
<style>
.gradient {
  background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
}
</style>
<body class="leading-normal tracking-normal text-white gradient text-left font-semibold text-2xl" style="font-family: 'Source Sans Pro', sans-serif;">

<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nuevo registro de persona</h1>

  <%= render "form", persona: @persona %>

  <%= link_to 'Regresar a listado', personas_path, class: "text-gray-800 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
</body>

app/views/personas/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @persona %>

    <%= link_to 'Editar este registro', edit_persona_path(@persona), class: "text-gray-800 mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Eliminar persona', persona_path(@persona), method: :delete, class: "text-gray-800 mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Regresar a lista de personas', personas_path, class: "text-gray-800 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>
<%= content_tag :h1, current_user.welcome %> 

app/views/users/new.html.erb
gf

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="description" content="Simple landind page" />
    <style>
      .gradient {
        background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
      }
    </style>
  </head>
  <body class="leading-normal tracking-normal text-white gradient" style="font-family: 'Source Sans Pro', sans-serif;">
    <div class="grid grid-cols-6 gap-4 w-full mt-28">
      <div class="col-start-2 col-span-4 text-center text-4xl">¡Hola bienvenido!</div> 
        <div id="navAction" class="col-start-3 col-end-5 w-full text-center w-3/12 mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full mt-4 lg:mt-0 py-4 px-8 shadow opacity-75 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
          
          <%= link_to 'Inicia sesión', ingresar_path%>
        </div>
          
    </div>
  </body>
</html>